application: your-application-id-here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- appstats: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: endpoints
  version: "latest"
- name: pycrypto
  version: "latest"

inbound_services:
- warmup

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?\.bak
- ^(.*/)?.*/tests/.*
- ^(.*/)?.*/data/.*
- ^(.*/)?.*/google_appengine/.*
- ^(.*/)?.*/myenv/.*
- ^(.*/)?.*/css/sass/.*

error_handlers:
  - file: templates/default_error.html

handlers:
- url: /_ah/pipeline(/.*)?
  script: pipeline.handlers._APP

- url: /a/(.*)/_ah/pipeline(/.*)?
  script: pipeline.handlers._APP

- url: /_ah/spi/.*
  script: main.api

- url: /_ah/queue/deferred
  script: main.deferred_app
  login: admin

- url: /livecount/counter_admin
  script: livecount.counter_admin.application
  login: admin

- url: /livecount/.*
  script: livecount.counter.application
  login: admin

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: myApp/static/img/favicon.ico
  upload: myApp/static/img/favicon.ico


- url: .*  # This regex directs all routes to main.app
  script: main.app
